### ISSUE TITLE
백엔드 요청 사항 - 회원 탈퇴 (배포 환경)

### ISSUE THREAD

**Issue by sfdjsh** [teamprojectinfrean1/Frontend#30]
**\* 로컬 서버에서는 정상적으로 작동되는 것으로 확인**

### API 주소
- api/v1/member

### 문제 상황
1. 회원 탈퇴 요청 시, 500 에러를 반환

### 수정 요청 사항
1. 회원 탈퇴 요청 시, 500 에러 반환에 대한 확인 요청

**Comment by sooparkdev** [comment]
로컬 서버에서는 제대로 작동하지만, 배포 서버에서는 작동하지 않는 것을 확인 @ondjj

**Comment by ondjj** [comment]
@sfdjsh @sooparkdev 해당 이슈 해소 했습니다.

**Comment by sfdjsh** [comment]
@ondjj 다른 계정은 회원 탈퇴가 잘 진행되는 것으로 확인했는데, 아이디가 `tkdltprp0212` 인 계정은 현재 회원 탈퇴가 진행되고 있지 않은 상황입니다. 원인을 알 수 있을까요?

**Comment by ondjj** [comment]
@sfdjsh 
서버 재시작 해서 로그가 날아갔어요. 다시 요청해주시겠어요?

**Comment by sooparkdev** [comment]
@sfdjsh 의문점 해소 됐을까요?

**Comment by sfdjsh** [comment]
@ondjj @sooparkdev 아직 해결하지 못했습니다. 제가 내일 개인적으로 창준님께 연락드리겠습니다.

**Comment by ondjj** [comment]
@sfdjsh 내일 편하신 시간대 맞춰볼게요
