### ISSUE TITLE
프로젝트 수정 사항_1 - 메인 프로젝트 변경

### ISSUE THREAD

**Issue by sfdjsh** [teamprojectinfrean1/Frontend#36]
### 설명
현재 메인(별)인 프로젝트를 다른 프로젝트로 변경 후, 다시 메인이였던 프로젝트를 메인으로 설정하려고 하면 별이 체크 안되는 이슈 발생.

### 녹화 영상

https://github.com/teamprojectinfrean1/Frontend/assets/97646788/db5abe37-30ef-495e-98c0-ec20709af7d8

**Comment by sooparkdev** [comment]
이 이슈는 지난 주에 제가 디스코드에서 효리님께 말씀드렸고, 현재 디버깅 중에 있음을 알려드립니다
