### ISSUE TITLE
프로젝트 수정 사항_2 - 새 프로젝트 추가

### ISSUE THREAD

**Issue by sfdjsh** [teamprojectinfrean1/Frontend#37]
### 설명
새 프로젝트 추가 버튼을 클릭하고, 프로젝트를 생성하지 않고 다른 프로젝트를 가는 경우 NotFoundPage 로 이동하는 이슈 발생

### 녹화 영상

https://github.com/teamprojectinfrean1/Frontend/assets/97646788/63c8e8ac-c3b5-4eb1-a3d8-52dda1d5818a

**Comment by hyori100** [comment]
백엔드 오류이긴하지만 null 처리 누락의 원인도 있었어서 수정하여 push 했습니다.
