### ISSUE TITLE
프로젝트 수정 사항_3 - 프로젝트 생성

### ISSUE THREAD

**Issue by sfdjsh** [teamprojectinfrean1/Frontend#38]
### 설명
프로젝트를 생성한 직후, NotFoundPage 로 이동.
NotFoundPage 에서 메인 페이지로 돌아가기 버튼을 클릭하면 프로젝트 페이지로 정상적으로 이동

### 녹화 영상

https://github.com/teamprojectinfrean1/Frontend/assets/97646788/071c74aa-7432-4fe4-a80d-11784c4d1613

**Comment by hyori100** [comment]
이 부분도 백엔드 오류입니다

**Comment by hyori100** [comment]
백엔드 오류이긴하지만 null 처리 누락의 원인도 있었어서 수정하여 push 했습니다.
