### ISSUE TITLE
프로젝트 수정 사항_4 - 새로고침

### ISSUE THREAD

**Issue by sfdjsh** [teamprojectinfrean1/Frontend#39]
### 설명
프로젝트 페이지나 태스크 페이지에서 새로고침을 하게 되면, 프로젝트와 태스크 모두 사라지는 이슈 발생

### 녹화 영상

https://github.com/teamprojectinfrean1/Frontend/assets/97646788/83b35c5c-7cb3-4a2a-9daf-598e51aafe89

**Comment by sooparkdev** [comment]
"프로젝트와 태스크가 모두 사라진다"는 말씀이, 상단 탭에 있는 프로젝트 콤보 박스가 화면에서 사라지고, 사이드 탭이 클릭되지 않는다는 의미인가요?

**Comment by sfdjsh** [comment]
네 맞습니다.

**Comment by hyori100** [comment]
수정하여 push 했습니다.
