### ISSUE TITLE
태스크 수정 사항_1 - 태스크 생성

### ISSUE THREAD

**Issue by sfdjsh** [teamprojectinfrean1/Frontend#40]
### 설명
태스크 생성 후, 다시 태스크 생성을 하게 되면, 전에 생성되었던 태스크 제목이 남아있는 이슈 발생

### 녹화 영상
 
https://github.com/teamprojectinfrean1/Frontend/assets/97646788/5c4d5e62-1bc3-428e-9d7f-6004e748f37e

**Comment by hyori100** [comment]
수정하겠습니다

**Comment by sfdjsh** [comment]
@hyori100 수정 완료한 상태일까요? 최신 버전인 main에서는 아직 해결되지 않아 보입니다.

**Comment by hyori100** [comment]
수정하여 push 하였습니다~
