### ISSUE TITLE
태스크 수정 사항_2 - 태스크 내용 수정

### ISSUE THREAD

**Issue by sfdjsh** [teamprojectinfrean1/Frontend#41]
### 설명
1번 태스크의 내용을 수정하고, 2번 태스크를 클릭했을 때, 1번 태스크의 수정 내용이 보여지는 이슈 발생
태스크를 닫고 다시 열면 기존의 태스크의 내용이 보여짐.

### 녹화 영상

https://github.com/teamprojectinfrean1/Frontend/assets/97646788/bb10d15f-efd5-481c-88a3-c5ef0a092eb4

**Comment by hyori100** [comment]
수정하겠습니다

**Comment by hyori100** [comment]
수정해서 push 했습니다
