### ISSUE TITLE
태스크 수정 사항_3 - 태스크 날짜 수정

### ISSUE THREAD

**Issue by sfdjsh** [teamprojectinfrean1/Frontend#42]
### 설명
태스크 날짜를 수정하고 다시 수정한 태스크를 들어가는 경우, 변경한 날짜로 수정되지 않는 이슈 발생
날짜도 원하는 날짜로 수정되지 않은 이슈 발생 ex) 수정 날짜를 6월 25일 ~ 6월 30일로 수정하였지만, 잠시 후 확인해보면 6월 24일 ~ 6월 29일로 수정되어 있는 것을 확인.

### 녹화 영상
 
https://github.com/teamprojectinfrean1/Frontend/assets/97646788/224c4213-a216-4ccc-b57f-9cdb3512a6af

**Comment by sooparkdev** [comment]
해결하였습니다

**Comment by hyori100** [comment]
이거 테스크 관련 버그였는데 해결해주신 건가요...? main 브랜치에 push 안되어있는 것 같습니다.

**Comment by hyori100** [comment]
테스크 관련해서는 아직 수정중입니다!

**Comment by hyori100** [comment]
수정해서 push 했습니다
