### ISSUE TITLE
태스크 수정 사항_4 - 태스크 조회

### ISSUE THREAD

**Issue by sfdjsh** [teamprojectinfrean1/Frontend#43]
### 설명
태스크 목록이 2번 페이지까지 있는 프로젝트에서 2번 페이지의 태스크를 보는 도중에, 태스크 목록이 1번 페이지까지 있는 프로젝트를 이동할 시, 태스크 목록이 안보이는 이슈 발생 ( < 버튼을 눌러야 태스크가 보임)

### 녹화 영상

https://github.com/teamprojectinfrean1/Frontend/assets/97646788/0230812a-4802-45fe-98d0-25ce2a1d293e

**Comment by hyori100** [comment]
아이고 이런 문제가... 수정하겠습니다

**Comment by hyori100** [comment]
수정해서 push 했습니다.
