### ISSUE TITLE
이슈 수정 사항_1 - 이슈 생성 시 담당자 오류

### ISSUE THREAD

**Issue by sfdjsh** [teamprojectinfrean1/Frontend#44]
### 설명
이슈 생성 시, 담당자를 선택하지 않고 이슈를 생성할 경우, 문제가 발생. 
담당자를 선택 안하고 생성을 시도했을 때를 고려.

### 녹화 영상

https://github.com/teamprojectinfrean1/Frontend/assets/97646788/f7192064-a69f-49a9-947e-96b5a73e95c7

**Comment by sooparkdev** [comment]
서버 측에서 발생한 500 에러임을 확인했습니다. 제 추측으로는 이슈를 생성할 때 담당자 값을 null로 설정할 수 있도록 허용하기로 한 사항이 최신 배포된 서버에 반영되지 않은 것 같습니다. 
@ondjj 확인 부탁드립니다

**Comment by sooparkdev** [comment]
로컬 서버에서는 문제가 없지만, 배포 서버에서만 문제가 발생하는 것을 확인 @ondjj

**Comment by ondjj** [comment]
@sooparkdev @sfdjsh 

- 배포 환경 스키마 문제 확인했습니다. (수정 완료)
- UI로 확인하는 작업을 진행하려고 하는데, 아래와 같이 반응이 없거나 요청이 거절당하고 있어 테스트를 못 했어요.


![스크린샷 2024-07-02 오후 5 57 00](https://github.com/teamprojectinfrean1/Frontend/assets/86146128/5420d43e-09e5-413a-9a34-9c3728e0d5a0)

**Comment by sooparkdev** [comment]
로컬과 배포 환경에서 UI로 테스트하고 잘 작동하는 것 확인했습니다
