### ISSUE TITLE
이슈 수정 사항_2 - 이슈 생성 및 수정 (기간)

### ISSUE THREAD

**Issue by sfdjsh** [teamprojectinfrean1/Frontend#45]
### 설명
기간을 설정하고 생성 시, 선택한 기간과 일치하지 않은 이슈 발생
이슈를 클릭하여 기간을 설정하고 수정 시, 선택한 기간과 일치하지 않은 이슈 발생

- 정상적으로 작동된 적도 있고, 안되는 적도 있음. (랜덤으로 발생)

### 녹화 영상

1. 이슈 생성 시 날짜 오류
선택한 기간 2024.06.26 ~ 2024.06.27 -> 실제로 생성된 기간 : 2024.06.25 ~ 2024.06.26

https://github.com/teamprojectinfrean1/Frontend/assets/97646788/61e1ec59-b1e0-4363-8e91-18f416f2170c

2. 이슈 수정 시 날짜 오류
선택한 기간 2024.06.24 ~ 2024.06.28 -> 실제로 수정된 기간 : 2024.06.24 ~ 2024.06.27

https://github.com/teamprojectinfrean1/Frontend/assets/97646788/8d293585-1dca-4859-b1ca-d50f24fe7ed0

**Comment by sooparkdev** [comment]
UI에서 사용자가 선택한 로컬 시간을 UTC 시간으로 변환하는 과정에서 발생한 문제임을 확인하였습니다. 저희 웹앱은 현재 단일 시간대 사용자만을 지원하므로, 이러한 요구사항에 맞춰 UTC 변환 로직을 제거하였습니다. 해당 변경 사항은 이미 메인 브랜치에 머지되었으며, 날짜 미일치 문제가 해결되었음을 알려드립니다. 확인해 보시고 추가적인 피드백 있으시면 알려주세요.

**Comment by sfdjsh** [comment]
확인했습니다!
