### ISSUE TITLE
가입 후 사용자 프로필 이미지 변경 불가 

### ISSUE THREAD

**Issue by sooparkdev** [teamprojectinfrean1/Frontend#48]
### 설명
 사용자가 계정 생성 시 프로필 이미지를 업로드할 때는 문제가 없습니다. 하지만 가입 후 사용자 프로필에서 이미지를 변경하려 할 때, 이미지 수정이 반영되지 않는 문제가 발생합니다. 로컬과 배포 환경 모두에서 문제가 발생합니다.

**Comment by sooparkdev** [comment]
1. "회원 가입 진행 시 프로필 이미지 업로드 하는 항목이 없는 거 같다"라는 말씀이 UI에서 사용자가 이미지를 올릴 수 있는 기능이 없다는 말씀이실까요? 아니면 회원가입 요청을 보낼 때 프로필 이미지 속성이 오지 않는다는 말씀이실까요? 
 
2. 현재 프론트에서는 서버 응답으로 받은 이미지 속성 값이 null인 경우 자체적으로 기본 프로필 이미지를 표시하고 있습니다. 이 이미지를 백엔드에서도 꼭 저장할 필요성이 있는지 궁금합니다. 백엔드에서 null, 빈문자열, 또는 다른 값으로 저장해두는 방식은 문제가 있을 수 있나요?

**Comment by ondjj** [comment]
1. 제가 발견을 못 했네요 이미지 업로드 버튼이 따로 있을거라 생각했어요
2. 이 부분은 NULL일 경우 저장 자체를 안하도록 로직을 변경했으니 무시하셔도 좋을거같아요!

**Comment by sooparkdev** [comment]
1. 사용자가 혼란스러워할 수 있는 인터페이스 디자인인 것 같네요! 오른쪽 하단에 플러스 버튼을 추가하는 등 다른 개선 방법을 생각해보겠습니다.
![image](https://github.com/teamprojectinfrean1/Frontend/assets/135008690/244de9f0-05a0-4f3c-a1ca-1197e18f67cd)

2. 네!

**Comment by sfdjsh** [comment]
@sooparkdev 혹시 이슈 해결되었나요? 일단 저는 마이페이지에서 이미지 변경이 잘 되고 있습니다.

**Comment by sooparkdev** [comment]
UI로 테스트하고 잘 작동하는 것 확인했습니다
