### ISSUE TITLE
프로젝트 수정 사항_5 - 프로젝트 생성 시 제목 공백 설정

### ISSUE THREAD

**Issue by sfdjsh** [teamprojectinfrean1/Frontend#50]
### 설명
프로젝트 생성 시 제목에 공백을 추가하여 생성할 경우, 사용자들이 불편할 수 있으므로 왼쪽과 오른쪽의 공백을 제거하는 trim을 적용하는 것이 좋아 보임

### 녹화 영상

https://github.com/teamprojectinfrean1/Frontend/assets/97646788/a54fcad5-8d6f-4ccc-b276-de928854c560

**Comment by hyori100** [comment]
수정하여 push 하였습니다.
